---
- name: Creation of VPC in OHIO region
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC variables
      include_vars: vars/vpc_setup
    - name: create a VPC with default tenancy and a couple of tags
      ec2_vpc_net:
        name: vprofile-vpc
        cidr_block: '{{ vpcCidr }}'
        region: '{{ region }}'
        tags:
          Name: vprofile-vpc-pro
          project: vprofile
        tenancy: default
      register: vpc_register

    - name: Creation of  1 public subnets
      ec2_vpc_subnet:
          state: '{{ state }}'
          vpc_id: '{{ vpc_register.vpc.id }}'
          region: '{{ region }}'
          az: '{{ zone1 }}'
          cidr: '{{ PubSub1Cidr }}'
          map_public: yes
          tags:
             Name: public-Subnet1-vprofile
      register: public_subnet1
    - name: Creation of  2 public subnets
      ec2_vpc_subnet:
        state: '{{ state }}'
        vpc_id: '{{ vpc_register.vpc.id }}'
        region: '{{ region }}'
        az: '{{ zone2 }}'
        cidr: '{{ PubSub2Cidr }}'
        map_public: yes
        tags:
          Name: public-Subnet2-vprofile
      register: public_subnet2
    - name: Creation of  3 public subnets
      ec2_vpc_subnet:
        state: '{{ state }}'
        vpc_id: '{{ vpc_register.vpc.id }}'
        region: '{{ region }}'
        az: '{{ zone3 }}'
        cidr: '{{ PubSub3Cidr }}'
        map_public: yes
        tags:
            Name: public-Subnet3-vprofile
      register: public_subnet3
    - name: Creation of  1 private subnets
      ec2_vpc_subnet:
        state: '{{ state }}'
        vpc_id: '{{ vpc_register.vpc.id }}'
        region: '{{ region }}'
        az: '{{ zone1 }}'
        cidr: '{{ PrivSub1Cidr }}'
        tags:
            Name: private-Subnet1-vprofile
      register: private_subnet1
    - name: Creation of  2 private subnets
      ec2_vpc_subnet:
        state: '{{ state }}'
        vpc_id: '{{ vpc_register.vpc.id }}'
        region: '{{ region }}'
        az: '{{ zone2 }}'
        cidr: '{{ PrivSub2Cidr }}'
        tags:
          Name: private-Subnet2-vprofile
      register: private_subnet2
    - name: Creation of  3 private subnets
      ec2_vpc_subnet:
        state: '{{ state }}'
        vpc_id: '{{ vpc_register.vpc.id }}'
        region: '{{ region }}'
        az: '{{ zone3 }}'
        cidr: '{{ PrivSub3Cidr }}'
        tags:
          Name: private-Subnet3-vprofile
      register: private_subnet3
###creation of internet Gateway and route tables
    - name: internet gateway creation
      ec2_vpc_igw:
        vpc_id: '{{ vpc_register.vpc.id }}'
        state: '{{ state }}'
        region: '{{ region }}'
      register: igw
###creation of route table and associate subnet with it
    - name: Set up public subnet route table
      ec2_vpc_route_table:
        vpc_id: '{{ vpc_register.vpc.id }}'
        region: '{{ region }}'
        tags:
          Name: Vprofile-Route-Table
        subnets:
          - "{{ public_subnet1.subnet.id }}"
          - "{{ public_subnet2.subnet.id }}"
          - "{{ public_subnet3.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw.gateway_id }}"
      register: public_route_table
    - debug:
         msg: '{{ item }}'
      loop:
         -  '{{ vpc_register.vpc.id }}'
         -  '{{ public_subnet1.subnet.id }}'
         -  '{{ public_subnet2.subnet.id }}'
         -  '{{ public_subnet3.subnet.id }}'
         -  '{{ igw.gateway_id }}'
         -  '{{ public_route_table.route_table.id }}'
    - copy:
         content: '{{ item }}'
         dest: ./local-var
