---
- name: vprofile stack setup
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: import vpc id detail
      include_vars: vars/output_vars
    - name: import vprostacksetup variable
      include_vars: vars/vprostacksetup

    - name: creation of keypair
      ec2_key:
        name: vpro-key
        region: '{{ region }}'
      register: keypair

    - name: Save the pem key to local file if new keypair generated
      copy:
         content: '{{ keypair.key.private_key }}'
         dest: ./vprofile.pem
         mode: 0600
      when: keypair.changed
